//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPizzaria.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoPizzaria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registrar.
        /// </summary>
        internal static string btnCadastrar_Text {
            get {
                return ResourceManager.GetString("btnCadastrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string btnCancelar_Text {
            get {
                return ResourceManager.GetString("btnCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string btnEditar_Text {
            get {
                return ResourceManager.GetString("btnEditar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string btnExcluir_Text {
            get {
                return ResourceManager.GetString("btnExcluir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inserir.
        /// </summary>
        internal static string btnInserir_Text {
            get {
                return ResourceManager.GetString("btnInserir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP.
        /// </summary>
        internal static string cepToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cepToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente.
        /// </summary>
        internal static string clientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_FILL0_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("delete_FILL0_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_FILL0_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("edit_FILL0_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a nsei.
        /// </summary>
        internal static string exibirToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exibirToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário.
        /// </summary>
        internal static string funcionarioToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("funcionarioToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Igrediente.
        /// </summary>
        internal static string igredientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("igredientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TEsteLavbel.
        /// </summary>
        internal static string label123_Text {
            get {
                return ResourceManager.GetString("label123.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        internal static string lbBairro_Text {
            get {
                return ResourceManager.GetString("lbBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNH.
        /// </summary>
        internal static string lbCarteiraMotorista_Text {
            get {
                return ResourceManager.GetString("lbCarteiraMotorista.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Catergoria.
        /// </summary>
        internal static string lbCategoria_Text {
            get {
                return ResourceManager.GetString("lbCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep.
        /// </summary>
        internal static string lbCep_Text {
            get {
                return ResourceManager.GetString("lbCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        internal static string lbCidade_Text {
            get {
                return ResourceManager.GetString("lbCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string lbCpf_Text {
            get {
                return ResourceManager.GetString("lbCpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cv.
        /// </summary>
        internal static string lbCv_Text {
            get {
                return ResourceManager.GetString("lbCv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string lbDescricao_Text {
            get {
                return ResourceManager.GetString("lbDescricao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        internal static string lbEmail_Text {
            get {
                return ResourceManager.GetString("lbEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string lbId_Text {
            get {
                return ResourceManager.GetString("lbId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Igredientes.
        /// </summary>
        internal static string lbIgredientes_Text {
            get {
                return ResourceManager.GetString("lbIgredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imagem.
        /// </summary>
        internal static string lbImagem_Text {
            get {
                return ResourceManager.GetString("lbImagem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        internal static string lbLogradouro_Text {
            get {
                return ResourceManager.GetString("lbLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matricula.
        /// </summary>
        internal static string lbMatricula_Text {
            get {
                return ResourceManager.GetString("lbMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string lbNome_Text {
            get {
                return ResourceManager.GetString("lbNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País.
        /// </summary>
        internal static string lbPais_Text {
            get {
                return ResourceManager.GetString("lbPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string lbSenha_Text {
            get {
                return ResourceManager.GetString("lbSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string lbTamanho_Text {
            get {
                return ResourceManager.GetString("lbTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string lbTelefone_Text {
            get {
                return ResourceManager.GetString("lbTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        internal static string lbTipo_Text {
            get {
                return ResourceManager.GetString("lbTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uf.
        /// </summary>
        internal static string lbUf_Text {
            get {
                return ResourceManager.GetString("lbUf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string lbUnidadeMedida_Text {
            get {
                return ResourceManager.GetString("lbUnidadeMedida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        internal static string lbUsuario_Text {
            get {
                return ResourceManager.GetString("lbUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade.
        /// </summary>
        internal static string lbValidade_Text {
            get {
                return ResourceManager.GetString("lbValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string lbValor_Text {
            get {
                return ResourceManager.GetString("lbValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Borda.
        /// </summary>
        internal static string lbValorBorda_Text {
            get {
                return ResourceManager.GetString("lbValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedidos.
        /// </summary>
        internal static string pedidosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pedidosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_add_FILL0_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("person_add_FILL0_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        internal static string produtosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("produtosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabor.
        /// </summary>
        internal static string saboresToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saboresToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string toolStripStatusLabel1_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabel1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores.
        /// </summary>
        internal static string valoresPizzaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("valoresPizzaToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
