//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPizzaria.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoPizzaria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        internal static string btnCadastrar_Text {
            get {
                return ResourceManager.GetString("btnCadastrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancelar_Text {
            get {
                return ResourceManager.GetString("btnCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string btnCep_Text {
            get {
                return ResourceManager.GetString("btnCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string btnCliente_Text {
            get {
                return ResourceManager.GetString("btnCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string btnEditar_Text {
            get {
                return ResourceManager.GetString("btnEditar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string btnEndereco_Text {
            get {
                return ResourceManager.GetString("btnEndereco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string btnExcluir_Text {
            get {
                return ResourceManager.GetString("btnExcluir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionario.
        /// </summary>
        internal static string btnFuncionario_Text {
            get {
                return ResourceManager.GetString("btnFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        internal static string btnFuncionarios_Text {
            get {
                return ResourceManager.GetString("btnFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igredientes.
        /// </summary>
        internal static string btnIgrediente_Text {
            get {
                return ResourceManager.GetString("btnIgrediente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        internal static string btnInserir_Text {
            get {
                return ResourceManager.GetString("btnInserir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string btnProduto_Text {
            get {
                return ResourceManager.GetString("btnProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabores.
        /// </summary>
        internal static string btnSabores_Text {
            get {
                return ResourceManager.GetString("btnSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        internal static string btnValores_Text {
            get {
                return ResourceManager.GetString("btnValores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_FILL0_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("delete_FILL0_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_FILL0_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("edit_FILL0_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsei.
        /// </summary>
        internal static string exibirToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exibirToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrediente.
        /// </summary>
        internal static string igredientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("igredientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEsteLavbel.
        /// </summary>
        internal static string label123_Text {
            get {
                return ResourceManager.GetString("label123.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string lbBairro_Text {
            get {
                return ResourceManager.GetString("lbBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNH.
        /// </summary>
        internal static string lbCarteiraMotorista_Text {
            get {
                return ResourceManager.GetString("lbCarteiraMotorista.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catergoria.
        /// </summary>
        internal static string lbCategoria_Text {
            get {
                return ResourceManager.GetString("lbCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep.
        /// </summary>
        internal static string lbCep_Text {
            get {
                return ResourceManager.GetString("lbCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string lbCidade_Text {
            get {
                return ResourceManager.GetString("lbCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string lbCpf_Text {
            get {
                return ResourceManager.GetString("lbCpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cv.
        /// </summary>
        internal static string lbCv_Text {
            get {
                return ResourceManager.GetString("lbCv.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string lbDescricao_Text {
            get {
                return ResourceManager.GetString("lbDescricao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lbEmail_Text {
            get {
                return ResourceManager.GetString("lbEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lbId_Text {
            get {
                return ResourceManager.GetString("lbId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igredientes.
        /// </summary>
        internal static string lbIgredientes_Text {
            get {
                return ResourceManager.GetString("lbIgredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        internal static string lbImagem_Text {
            get {
                return ResourceManager.GetString("lbImagem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        internal static string lbLogradouro_Text {
            get {
                return ResourceManager.GetString("lbLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricula.
        /// </summary>
        internal static string lbMatricula_Text {
            get {
                return ResourceManager.GetString("lbMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string lbNome_Text {
            get {
                return ResourceManager.GetString("lbNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string lbPais_Text {
            get {
                return ResourceManager.GetString("lbPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string lbSenha_Text {
            get {
                return ResourceManager.GetString("lbSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string lbTamanho_Text {
            get {
                return ResourceManager.GetString("lbTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string lbTelefone_Text {
            get {
                return ResourceManager.GetString("lbTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string lbTipo_Text {
            get {
                return ResourceManager.GetString("lbTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uf.
        /// </summary>
        internal static string lbUf_Text {
            get {
                return ResourceManager.GetString("lbUf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string lbUnidadeMedida_Text {
            get {
                return ResourceManager.GetString("lbUnidadeMedida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string lbUsuario_Text {
            get {
                return ResourceManager.GetString("lbUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validade.
        /// </summary>
        internal static string lbValidade_Text {
            get {
                return ResourceManager.GetString("lbValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string lbValor_Text {
            get {
                return ResourceManager.GetString("lbValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Borda.
        /// </summary>
        internal static string lbValorBorda_Text {
            get {
                return ResourceManager.GetString("lbValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        internal static string pedidosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pedidosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_add_FILL0_wght400_GRAD0_opsz40 {
            get {
                object obj = ResourceManager.GetObject("person_add_FILL0_wght400_GRAD0_opsz40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string produtosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("produtosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabor.
        /// </summary>
        internal static string saboresToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saboresToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string toolStripStatusLabel1_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabel1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        internal static string valoresPizzaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("valoresPizzaToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
